import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Image from "next/image";
import { Lobster, Pacifico } from "@next/font/google";
const lobster = Lobster({
  weight: "400",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
});
export default function Home() {
  // button click handler
  const handleClick = () => {
    alert("Btn clicked!");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>I love Coffee ☕ </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={[styles.title, lobster.className].join(" ")}>
          Coffee Cup!
        </h1>
        <Banner
          font={pacifico.className}
          buttonText={"Show My Coffee!"}
          handleClick={handleClick}
        />
        <div className={styles.cup_image}>
          <Image width={400} height={400} src="/coffee_cup.png" />
        </div>
      </main>
    </div>
  );
}
